spring:
  application:
    name: java-project-99

  datasource:
    url: jdbc:postgresql://dpg-d99u36v7f7vs73bch9jg-a.frankfurt-postgres.render.com:5432/java_project_db_mcmo
    username: java_project_db_mcmo_user
    password: 5hqaAFlvsBxMNXZp1OrjDYOtYps7EWw0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # в продакшне не меняем схему автоматически
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false              # не показываем SQL в логах продакшна