spring:
  application:
    name: java-project-99

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

# src/main/resources/certs/
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

