spring:
  application:
    name: java-project-99

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# src/main/resources/certs/
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://707f624659ab81a286c33bc6b4b046c2@o4511767759028224.ingest.de.sentry.io/4511767767220304
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true